### PR TITLE
Update 00-run-chroot.sh

### PR DESCRIPTION
**Pull request by Yes21**
Fixed issues : bad kernel-headers version, bad symlinks in /lib/modules/, wireshark-common asks a question

### CODE REVIEW

**Comment by Yes21** [comment]
Sorry, I did something bad.
The script can't install anymore any package.
I will look at the source lists, and find how to make it work properly.

**Comment by Yes21** [comment]
No, there's no problem with this PR.
The issue I have occurs in 04-Wifibroadcast/03-run-chroot.sh.
I'll investigate it now ...

**Comment by Yes21** [comment]
After a total rebuild I can confirm that :
- 4.14.71 kernel-headers version are installed by apt-get install raspberrypi-kernel-headers,
- bad symlinks in /lib/modules/ have disappear,
-  wireshark-common doen't ask anymore question.

But ... OSD is no more displayed !
Not sure if it's cause by this PR ...

**Comment by pilotnbr1** [comment]
Wireshark still asked me questions...

**Comment by Yes21** [comment]
No, this command is not part of the script, because kernel-headers are not installed in the image.
But if you need it (for compiling a module, or installing something else), then you have to use `apt-get install raspberrypi-kernel-headers` to get it. And now the command installs good versions of kernel-headers, and it also creates good symlinks `in /lib/modules/`.
Do you understand ?

**Comment by pilotnbr1** [comment]
So I did a complete clone and fresh start. 

The wireshark prompt does not appear during the build- however I did not yet check if the changes made just made wireshark not install. ie perhaps the changes made did not let wireshark install at all

On a pi 3b the script hangs while initializing the wifi adapter

The OSD never appears (because the adapter does not initialize)

@Yes21 I think we need a solution to the symlink/headers that does not require running 
install raspberrypi-kernel-headers on a live internet connected pi

While researching this problem I came across this interesting post-
https://stackoverflow.com/questions/16688138/building-lib-modules-uname-r-build-while-compiling-a-kernel

**Comment by Yes21** [comment]
> Wireshark still asked me questions...

I've just tested it again for the third time, and I can confirm that wireshark doesn't ask anymore a question.
The building process did go to the end without stopping. That's a great thing !

**Comment by Yes21** [comment]
> @Yes21 I think we need a solution to the symlink/headers that does not require running
install raspberrypi-kernel-headers on a live internet connected pi

@pilotnbr1 I don't understand what you mean ?
For me there's no more problem with that ...

@RespawnDespair Can you help me to explain things, because my english is too poor for that !
I'm sure that @pilotnbr1 and me are misunderstanding us ...

**Comment by Yes21** [comment]
> The wireshark prompt does not appear during the build- however I did not yet check if the changes made just made wireshark not install. ie **perhaps the changes made did not let wireshark install at all**

@pilotnbr1 You could be right !
It seems that wireshark-common isn't installed, and tshark also, which is normal because wireshark-common is needed for tshark.
That's certainly why OSD is not working anymore ...
Will continue to investigate.

**Comment by Yes21** [comment]
wireshark-common (and tshark) were not installed because I did disable `sudo apt-get update` !!
After having run `sudo apt-get update`, they can be installed without the question from wireshark.
But now I again have the problem of bad kernel-headers version with `apt-get install raspberrypi-kernel-headers` !!

This is the hell !! 

Now the first thing to do is to restore `sudo apt-get update`.
... and then find a way to install good kernel-headers version, if someone needs to install it.

**Comment by Yes21** [comment]
With wireshark-common (and tshark) correctly installed, OSD is not working again !

That's enough for tonight.

**Comment by pilotnbr1** [comment]
I think this pr should be reverted.

apt-get update does not actually make updates to the software. It only updates the list of sources and dependencies. I think that should be left in place. On a side note I think after all the packages are installed and purged we should run auto-remove to get rid of uneeded packages

Removing the symlinks, could be left for now but that really doesnt address the underlying problem of nothing in /usr/src

Wireshark is not installed

**Pull request merged**
